### PR TITLE
add react 19 to peer deps

### PR DESCRIPTION
**Pull request by jaredcbaum**
This PR:

- Adds React 19 to peer reps for the icons package

### CODE REVIEW

**Comment by mxa0079** [comment]
Please merge

**Comment by officiallerio** [comment]
please merge

**Comment by takefy-dev** [comment]
Please merge it omg

**Comment by codenomnom** [comment]
Uhm, is there any issue merging this? 🤔

**Comment by takefy-dev** [comment]
bro is just AFKOn 24 Oct 2024, at 12:56, codenomnom ***@***.***> wrote:﻿
Uhm, is there any issue merging this? 🤔

**Comment by onurhan1337** [comment]
great work.

**Comment by Gitstar-OC** [comment]
Please merge it ?

**Comment by needim** [comment]
you can use overrides for a temporary fix.

```json
"overrides": {
	"@radix-ui/react-icons": {
		"react": "$react"
	}
}
```

**Comment by rezarahem** [comment]
This should have been merged already. No issues here.

**Comment by takefy-dev** [comment]
the owner is AFK he is not working at radix anymore

**Comment by VibingCreator** [comment]
Merge you tyrant.

**Comment by guchris** [comment]
is there someone we can contact?

**Comment by officiallerio** [comment]
> is there someone we can contact?

the other stupid way we can do is by making nonsense PR on all radix repo by saying "merge the radix icons" for them to notice us

**Comment by Bantolinao** [comment]
please merge! why it take too long

**Comment by DysektAI** [comment]
Merge please, so the actual issues can be fixed...

**Comment by Scholar01** [comment]
https://github.com/radix-ui/primitives/issues/3195
I went to another library and raised an issue

**Review by aminekha — APPROVED** [review]
No issues

**Comment by priyeshghamandi** [comment]
Please merge

**Comment by DariusLukasukas** [comment]
Is this repo still maintained? Shadcn UI compatibility is blocked due to the pending Radix icons merge.

**Comment by takefy-dev** [comment]
No it’s not

**Comment by hsavit1** [comment]
cmon please merge this already

**Comment by Saptak-Bose** [comment]
merge this plsss...shadcn not working cause of this

**Comment by officiallerio** [comment]
try to put issues on other radix repo so that they will notice us.

**Review by priyeshghamandi — APPROVED** [review]
This is good. Please merge

**Comment by hackerharsh-77** [comment]
pl merge this as it is causing version mismatch in frameworks react 19^

**Comment by radioac7iv3** [comment]
Looks good to me, can we merge?

**Comment by officiallerio** [comment]
merge

**Comment by shadowoff09** [comment]
Please merge it, shadcn is broken because of this.

**Comment by officiallerio** [comment]
@chaance  @hadihallak please merge sir

**Comment by priyeshghamandi** [comment]
@chaance @hadihallak can you please merge this PR. It's blocking a lot of projects. Thanks,

**Comment by tyrellshawn** [comment]
@chaance @hadihallak  Please merge its blocking

**Review by tyrellshawn — APPROVED** [review]

**Comment by madebydor** [comment]
merge it for the love of shadcn

**Review by DariusLukasukas — APPROVED** [review]

**Comment by officiallerio** [comment]
:(

**Comment by priyeshghamandi** [comment]
@vladyslavmoroz @colmtuite @peduarte @loklaan  can you please merge this PR. It's blocking a lot of projects. Thanks,

**Review by napstar-420 — APPROVED** [review]

**Comment by napstar-420** [comment]
Please merge it man...., i can't init the shadcn ui

**Review by shadowoff09 — APPROVED** [review]

**Review by emirhangumus — APPROVED** [review]

**Review by heyjorgedev — APPROVED** [review]

**Comment by diegohaz** [comment]
I don't understand. Couldn't you just `npm install --force` while waiting for this?

**Comment by peduarte** [comment]
hide-hiding-gif

**Pull request merged**
