### PR TITLE
Update package.json to add support for React v19 and Next.js v15

### PR DESCRIPTION
**Pull request by ChrisGambrell**
---

PR checklist:

- [x] Figma: icon shapes use “Scale” constraint
- [x] Figma: icon components are sorted Z-A in the file
- [x] Figma: icon components are built with a single union or compound shape when possible
- [x] Figma: library changes are published
- [x] SVG: icons render correctly in a browser
- [x] SVG: icons are exported with `width="15" height="15" viewBox="0 0 15 15"`
- [x] SVG: no icons are exported with `stroke`
- [x] SVG: no icons are exported with `clip-path`
- [x] SVG: no icons exceed 5 KB
- [x] Website is up to date
- [x] Sketch file is up to date
- [x] IconJar file is up to date
  - [x] Icon names in the IconJar library are correct
  - [x] Version in the IconJar library description is correct

### CODE REVIEW

**Comment by kamami** [comment]
Please merge this.

**Comment by wengkitt** [comment]
Please merge this.

**Comment by cavdarfr** [comment]
I think it's ready to merge...

**Comment by wengkitt** [comment]
Temporary Fix

https://github.com/radix-ui/icons/pull/184#issuecomment-2436109770

**Comment by ChrisGambrell** [comment]
@chaance @hadihallak please merge?

**Comment by tetraf0ur** [comment]
pls merge

**Pull request closed without merging**
